src/unpackaged/objects/Dreamhouse_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Slack_Property_Webhook_URL__c</fullName>
        <label>Slack Property Webhook URL</label>
        <type>Url</type>
    </fields>
    <label>Dreamhouse</label>
</CustomObject>

src/unpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PostPriceChangeToSlack.cls
public class PostPriceChangeToSlack {

    @InvocableMethod(label='Post Price Change Notification to Slack')
    public static void postToSlack(List<Id> propertyId) {
		String slackURL;
	    Dreamhouse_Settings__c settings = Dreamhouse_Settings__c.getOrgDefaults();
        if (!Test.isRunningTest()) {
        	if (settings == null || settings.Slack_Property_Webhook_URL__c == null) {
		        System.Debug('Slack_Property_Webhook_URL not set. Aborting PostPriceChangeToSlack process action');
                return;
            } else {
            	slackURL = settings.Slack_Property_Webhook_URL__c;   
            }
        }
        Id propId = propertyId[0]; // If bulk, only post first to avoid spamming
        Property__c property = [SELECT Address__c, City__c, State__c, Price__c from Property__c WHERE Id=:propId];
        String message = 'Price change: ' + property.Address__c + ', ' + property.City__c + ' ' + property.State__c + ' is now *$' + property.Price__c.setScale(0).format() + '*';
        System.Debug(message);
        
		Map<String,Object> payload = new Map<String,Object>();
		payload.put('text', message);
		payload.put('mrkdwn', true);
        String body = JSON.serialize(payload);    
        System.Debug(body);
        System.enqueueJob(new QueueableSlackCall(slackURL, 'POST', body));
    }
    
    public class QueueableSlackCall implements System.Queueable, Database.AllowsCallouts {
        
        private final String url;
        private final String method;
        private final String body;
        
        public QueueableSlackCall(String url, String method, String body) {
            this.url = url;
            this.method = method;
            this.body = body;
        }
        
        public void execute(System.QueueableContext ctx) {
            HttpRequest req = new HttpRequest();
            req.setMethod(method);
            req.setBody(body);
            Http http = new Http();
            HttpResponse res;
			if (!Test.isRunningTest()) {
	            req.setEndpoint(url);
				res = http.send(req);
        	}
        }

    }
    
}