src/unpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/YelpDemo/main/default/classes/YelpDemoController.cls
public class YelpDemoController {    
    
    @AuraEnabled
    public static String objectSelect(String objectType, Id recordId) {
        if (objectType.toLowercase() == 'account') {
            return accountSelect(recordId);
        } else if (objectType.toLowercase() == 'contact') {
            return contactSelect(recordId);
        } else if (objectType.toLowercase() == 'property__c') {
            return propertySelect(recordId);
        } else {
            // This is an error....
            return null;
        }
    }

    public static String contactSelect (Id recordId) {
        Contact contact = [SELECT MailingStreet, MailingCity, MailingState FROM Contact WHERE Id=:recordId];
        String location = contact.MailingStreet + ',' + contact.MailingCity + ',' + contact.MailingState;
        return location;
    }
    
    public static String propertySelect (Id recordId) {
        Property__c property = [SELECT Address__c, City__c, State__c FROM Property__c WHERE Id=:recordId];
        String location = property.Address__c + ',' + property.City__c + ',' + property.State__c;
        return location;
    }

    public static String accountSelect (Id recordId) {
        Account account = [SELECT BillingStreet, BillingCity, BillingState FROM Account WHERE Id=:recordId];
        String location = account.BillingStreet + ',' + account.BillingCity + ',' + account.BillingState;
        return location;
    }
}